<?php

namespace Admin\Controller;

use Svi\HttpBundle\Forms\Form;
use Svi\OrmBundle\Entity;
use Svi\SettingsBundle\BundleTrait;
use Svi\SettingsBundle\Entity\Setting;

class AdminSettingsController extends CrudController
{
    use BundleTrait;

    public function indexAction()
    {
        $this->getSettingsService()->updateDatabase();

        return parent::indexAction(); // TODO: Change the autogenerated stub
    }

    /**
     * @param Form $form
     * @param Setting $entity
     */
    protected function buildForm(Form $form, Entity $entity)
    {
        $form
            ->add('value', $this->getSettingsService()->getSettingType($entity->getKey()), [
                'label' => 'Значение',
                'data'  => $entity->getValue(),
            ]);
    }

    protected function getEntityIdColumnName()
    {
        return 'skey';
    }

    protected function getEntityIdFieldName()
    {
        return 'key';
    }

    protected function getListColumns()
    {
        return [
            'key'   => [
                'title' => 'Параметр',
                'value' => function (Setting $setting) {
                    return $this->getSettingsService()->getSettingName($setting->getKey());
                },
            ],
            'value' => [
                'title' => 'Значение',
                'value' => function (Setting $setting) {
                    if ($this->getSettingsService()->getSettingType($setting->getKey()) === 'password') {
                        return preg_replace('/.{1}/', '*', $setting->getValue());
                    } else {
                        return mb_substr($setting->getValue() . '', 0, 32, 'utf8');
                    }
                },
            ],
        ];
    }

    protected function getRoutes()
    {
        return [
            'edit' => '_panel_settings_edit',
        ];
    }

    protected function getManager()
    {
        return $this->getSettingManager();
    }

}